### ISSUE TITLE
Restriction not taking effect

### ISSUE THREAD

**Issue by devryb** [KaiKikuchi/DimRestrictor#3]
Restriction set for 20 players, there are currently 25 players on however people can still access the twilight.  Doesn't work with teleporting there via command or portal.
Had others test as well.

http://puu.sh/gdZ9T/183388c38c.png

**Comment by KaiKikuchi** [comment]
This plugin restrict the number of player on a world. It means that if you set restriction for DIM-7 to 20 players, it won't let more than 20 players to be on DIM-7.
Your screenshot shows the players list on your server (all dimensions).

**Comment by devryb** [comment]
Oh.. I meant for total players on the server but this is nice too... hmm. possible to add both ways?

**Comment by KaiKikuchi** [comment]
Yup, I'll work on it!

**Comment by KaiKikuchi** [comment]
Done.
