### ISSUE TITLE
Allow access based on the number of connected player

### ISSUE THREAD

**Issue by Yselith** [KaiKikuchi/DimRestrictor#4]
Hello,

It could be fun to let people access the dimension if there is 1-20 players, but if there is 20+ player it close the access.

The main problem is, what happen if every minutes a player join and left.

That should be, if there is 20-25 players during 5 minutes then close the access ?

**Comment by KaiKikuchi** [comment]
Hello! This suggestion is the same as #3 
I'm already working on it ;)

**Comment by Yselith** [comment]
Perfect !

**Comment by KaiKikuchi** [comment]
Just to clarify, the script won't expel players that are already on a restricted dimension.

Example:
DIM-7 is restricted to 10 players.
There are 9 players on the server, 2 of them on DIM-7.
5 players join the server. Nobody can't teleport to DIM-7 until the number of connected player is 10 or less. Those 2 players on DIM-7 are still there, and won't be automatically removed from DIM-7.

At this stage, the plugin check the number of player on that dimension, not the total number of players connected on a server.

**Comment by KaiKikuchi** [comment]
Done.
